[versions]
spring = "6.1.13"
spring-framework = "3.3.4"
spring-dependency-managment = "1.1.6"
junit-jupiter = "5.10.3"

[libraries]

spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
spring-framework-boot = { id = "org.springframework.boot", version.ref = "spring-framework" }
spring-dependency-managment = { id = "io.spring.dependency-management", version.ref = "spring-dependency-managment" }